[package]
name = "aoc-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "cookies"] }
scratch = "1"
thiserror = "1"
tracing = ">=0.1.36"
url = "2"
